// Generates out/sw.js after `next build`. Run: node scripts/gen-sw.mjs
//
// The export is a fixed set of files, so the service worker is generated from
// it rather than authored per-route: walk `out/`, emit the whole precache list
// under a content-hash cache name. No route-level cleverness, no runtime
// caching heuristics — install everything, serve cache-first, and the plane
// guarantee stops depending on HTTP-cache luck.
//
// Scope boundary: the built app only. Never IndexedDB, never captures, no
// background sync, no push. Bank data and app shell stay in separate storage
// domains on purpose.

import { createHash } from "node:crypto";
import { readFile, readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";

const OUT = path.join(import.meta.dirname, "..", "out");
const SHELL = "/index.html";

async function walk(dir) {
  const found = [];
  for (const name of await readdir(dir)) {
    if (name.startsWith(".")) continue;
    const full = path.join(dir, name);
    if ((await stat(full)).isDirectory()) found.push(...(await walk(full)));
    else found.push(full);
  }
  return found;
}

const files = (await walk(OUT))
  .map((f) => path.relative(OUT, f).split(path.sep).join("/"))
  .filter((f) => f !== "sw.js")
  .sort();

if (!files.includes("index.html")) {
  throw new Error("out/index.html missing — run `next build` first");
}

// the cache name changes only when a byte of the export changes; a new name is
// what installs a new cache and cleans the old one on activate
const digest = createHash("sha256");
for (const file of files) {
  digest.update(file);
  digest.update(createHash("sha256").update(await readFile(path.join(OUT, file))).digest());
}
const hash = digest.digest("hex").slice(0, 12);

// "/" is the manifest's start_url and the URL a home-screen launch requests,
// so it is precached as its own entry alongside the file it resolves to
const precache = ["/", ...files.map((f) => "/" + f.split("/").map(encodeURIComponent).join("/"))];

const sw = `// GENERATED by scripts/gen-sw.mjs — do not edit.
// Precaches the ${files.length}-file export under a content-hash cache name.
const CACHE = "kanahero-${hash}";
const SHELL = "${SHELL}";
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      for (const key of await caches.keys()) {
        if (key !== CACHE && key.startsWith("kanahero-")) await caches.delete(key);
      }
      await self.clients.claim();
    })(),
  );
});

// Cache-first, always. Offline the current cache serves forever; online the
// browser refetches this file, and a changed hash quietly becomes current on
// the next launch. No update UI.
self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  if (new URL(request.url).origin !== self.location.origin) return;

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const hit = await cache.match(request, { ignoreSearch: true });
      if (hit) return hit;
      try {
        return await fetch(request);
      } catch (err) {
        // a navigation to anything uncached still gets the app shell, which is
        // the whole app — there is no routing past it
        if (request.mode === "navigate") {
          const shell = await cache.match(SHELL);
          if (shell) return shell;
        }
        throw err;
      }
    })(),
  );
});
`;

await writeFile(path.join(OUT, "sw.js"), sw);

const bytes = (
  await Promise.all(files.map(async (f) => (await stat(path.join(OUT, f))).size))
).reduce((a, b) => a + b, 0);
console.log(
  `sw.js: kanahero-${hash} precaches ${precache.length} URLs (${(bytes / 1024 / 1024).toFixed(1)} MB)`,
);
